### PR TITLE
Update Gem dependencies

### PR DESCRIPTION
**Pull request by conorgil**
Add plugins for elasticsearch and S3, which are fluent
outputs that we were using previously to adopting StackDriver.

This is a partner PR to https://github.com/oasislabs/private-charts/pull/163 and https://github.com/oasislabs/private-ops/pull/1225.

### CODE REVIEW

**Review by ptrus — APPROVED** [review]

**Review by tjanez — APPROVED** [review]

**Comment by ptrus** [comment]
can we get this merged? @ravenac95  @conorgil

**Comment by conorgil** [comment]
@ptrus Yes, it can be merged. I would do it right now, but it needs a review approval. I leave it to you and @ravenac95 :)

**Comment by conorgil** [comment]
Oh wait... I see that you did approve this already. I wonder what's going on. Let me sort it out.

**Comment by conorgil** [comment]
Since I created the repo, I was the only one added as a collaborator. I just added the Dev Ops Admin team to be Admins on this repo, so you can all maintain it moving forward.

I will merge this PR now that your approvals register.

**Pull request merged**
